#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Bootstrap-SCSS
Version  : 3.3.7.1
Release  : 17
URL      : http://pypi.debian.net/XStatic-Bootstrap-SCSS/XStatic-Bootstrap-SCSS-3.3.7.1.tar.gz
Source0  : http://pypi.debian.net/XStatic-Bootstrap-SCSS/XStatic-Bootstrap-SCSS-3.3.7.1.tar.gz
Summary  : Bootstrap-SCSS 3.3.7 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-Bootstrap-SCSS-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-Bootstrap-SCSS
--------------
Bootstrap style library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Bootstrap-SCSS package.
Group: Default
Provides: xstatic-bootstrap-scss-python

%description python
python components for the XStatic-Bootstrap-SCSS package.


%prep
%setup -q -n XStatic-Bootstrap-SCSS-3.3.7.1

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
