#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Bootstrap-SCSS
Version  : 3.2.0.0
Release  : 8
URL      : https://pypi.python.org/packages/source/X/XStatic-Bootstrap-SCSS/XStatic-Bootstrap-SCSS-3.2.0.0.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-Bootstrap-SCSS/XStatic-Bootstrap-SCSS-3.2.0.0.tar.gz
Summary  : Bootstrap-SCSS 3.2.0 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-Bootstrap-SCSS-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-Bootstrap-SCSS
--------------
Bootstrap style library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Bootstrap-SCSS package.
Group: Default

%description python
python components for the XStatic-Bootstrap-SCSS package.


%prep
%setup -q -n XStatic-Bootstrap-SCSS-3.2.0.0

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
